### PR TITLE
Custom grid layout for achievements + FR translation fixes

### PR DESCRIPTION
**Pull request by Sym-O**
Here is a pull request for the grid layout to display achievements. We based our work on the alpha branch as you asked. To test it, you may have to revert the commit " Update ajax-functions.php" "fc8eb20a4741e56b56f42f4c250b0a331035f5eb". It causes problem on no-multi site.

### CODE REVIEW

**Comment by tw2113** [comment]
Some initial feedback for you.

With https://github.com/opencredit/badgeos/pull/409/files#diff-5fab46bfc21aa8883c35bb76463a268aL60, we would be applying the grid callback to all calls to badgeos_render_achievement, which we do not want to do. I also believe we can add that line to inside the badgeos_ajax_get_achievements function and have it still work. We would also be able to conditionally add it based on current layout choice.

I recommend the following on say line 166 before the WP_Query.

	if ( 'grid' == $layout ) {
		add_action( 'badgeos_render_achievement', 'custom_render_achievement' );
	}

With regards to https://github.com/opencredit/badgeos/pull/409/files#diff-2219338c0d88d07db6bbaae839dc647eL61, there's chance for us to bundle up selectors that set the same properties, so there's room to reduce there. Also, as odd as it may seem, we have thus far left responsive breakpoints up to the individual sites to take care of with their own needs.

For https://github.com/opencredit/badgeos/pull/409/files#diff-3c3876298821010282ba08aa4229d521R28 there are a number of places I have thoughts on. First is the function name, and this will apply to the add_action above as well. Since it would be a function added to BadgeOS core, it's safe to use a `badgeos_` prefix. Second of all would be the generic-ish name. It'd be better if it referenced the fact that it's a callback intended to provide markup better suited to be a grid. It would also be better placed in the `content-filters.php` file instead of the `ajax-functions.php` file. Lastly is the reliance on preg_replace. I see now where you utilize the `$layout` global, but I believe the conditional add_action will be a cleaner way to achieve the same result. After that, it's possible that we can copy/paste the original contents from `badgeos_render_achievement()` and alter as necessary to get the markup needed. We'd have full access to the achievement ID being used so that we could query for all the same parts as required.

Those are the main points I have, I won't nitpick about spacing issues and alignment, as that's easy enough to clean up afterwards. Feel free to respond to my points above and we can discuss best steps forward. I want your contributions to be top notch.

**Comment by tw2113** [comment]
With the other issued Pull Request, you're going to want to merge those changes into this branch and update the PR. As is, thanks to the other one going in, it won't merge cleanly any more.

**Comment by Sym-O** [comment]
Hi @tw2113 ,
I updated this branch and implement your suggestions of improvement before accepting this PR. Is it alright now ?

**Comment by tw2113** [comment]
Awesome Thanks :)

**Pull request merged**
