### PR TITLE
Capitalization for "Montrer Détails" et "Étapes Requises"

### PR DESCRIPTION
**Pull request by cyclingzealot**
Continuing correction of capitalization for French strings.

Don't merge yet, I will redo the .mo .

### CODE REVIEW

**Comment by cyclingzealot** [comment]
Redid the .mo file.

**Comment by tw2113** [comment]
Quick question, do you think this would also be needed for a possible 1.4.5 release? It'd be all bugfixes for what's already done up, but i18n may need touched on too.

**Comment by cyclingzealot** [comment]
I think I'm lacking context as I haven't worked that much on software development & releases with public git repos.  You mean 
* this particular commit
* the capitalisation throughout the  languages/badgeos-fr_FR.po file or 
* some FR strings missing?

Also, by "needed", you mean me needing or the French community needing?

In any case, no.  I can probably work around the lack of this commit being in 1.4.5.  As for the two latter, the amount of work having been done so far on French localization is impressive and you could probably get away with it.  it will probably irk some academics or French purists.

... not sure I answered the question though :-)

**Comment by tw2113** [comment]
Basically, I made a 1.4.5 branch yesterday that intends to provide a number of bug fixes, but wouldn't presently account for the french internationalization work you've done recently. Mostly just trying to see if I should pull in your changes as we before release to wordpress.org, or if it'd be fine to not have them for this point release and save for 1.5 :)

**Comment by cyclingzealot** [comment]
I'll manage.  Thanks for the thought.  My submodule is pointing at credil/badgeos.git .  So I guess I have to pull from either master or 1.4.5 of opencredit/badgeos.git, merge and then push to credil/badgeos.git

On the other hand, my version of poedit seems to be concanating strings over multiple lines.  If you don't mind that for the -fr_FR.po file, that would save me some time from merging changes every time I do a pull request.

**Comment by tw2113** [comment]
All of the changes in the 1.4.5 branch already exist in the alpha branch. As long as you keep going based on alpha, you shouldn't need to adjust anything.

**Pull request merged**
