### PR TITLE
Added Paragraph Markup for Unlogged User

### PR DESCRIPTION
**Pull request by X-Raym**
There is no markup for this text, which make it very hard to style it without touching the above title.
A simple paragraph and a class can do the trick.

### CODE REVIEW

**Comment by X-Raym** [comment]
A small thing than would be helpful :)

**Comment by tw2113** [comment]
This breaks the html. You start a paragraph, then close the previous unordered list, have the html comment, and then close the paragraph tag.

echo '<p class="widget-badgeos-non-logged-user"></ul></p>';

Also we'd need to have it PR'd against the alpha branch still.

**Comment by X-Raym** [comment]
Oups you are right I edited the file too fast, but you get the idea behind this FR.

**Comment by tw2113** [comment]
Unless I'm mistaken somehow, it's just ending up being an empty <p> tag here.

**Comment by X-Raym** [comment]
Oh you are right, that was a really poorly executed copy paste. I'll propose you a better request !

**Pull request closed without merging**
