### PR TITLE
Translation pt_BR

### PR DESCRIPTION
**Pull request by victorperin**
First translation time. 50% translated.
Must be revised for someone else.

### CODE REVIEW

**Comment by tw2113** [comment]
hey @victorperin do you think you could do a pull from alpha and re-check what you have for translations? Once it's accurate again, I'm willing to pull in what you have.

**Comment by victorperin** [comment]
Alright, I will do that, but I'll need some time to make it...

**Comment by solhuebner** [comment]
@victorperin could you update your translation? Would be a nice addition!

**Comment by the-wooninjas** [comment]
@victorperin Thankyou for your contribution. Adding it to the BadgeOS plugin now

**Pull request merged**
