### PR TITLE
Select2 update

### PR DESCRIPTION
**Pull request by asahi-badgeos**

### CODE REVIEW

**Comment by lkraav** [comment]
@asahi-badgeos this looks weird to me. You seem to have skipped 1.4.8.2 completely, which includes whole new functions like `badgeos_get_hidden_achievement_by_id()`, `badgeos_get_current_page_post_id()` and so forth. Can I help sync the github repo up with official plugins repo?

**Comment by asahi-badgeos** [comment]
Yes that would be great.

**Comment by lkraav** [comment]
> Yes that would be great.

@asahi-badgeos what's your current local development process? Is it SVN first then sync up GitHub manually or?

**Comment by asahi-badgeos** [comment]
@lkraav yes, that is how we did it for our last release, though going forward, I would like to sync GitHub first, and then release to SVN later.

**Comment by lkraav** [comment]
@asahi-badgeos let's roll with #574

**Comment by lkraav** [comment]
@asahi-badgeos gonna poke you a bit every now and then, hope you dont mind 🔢 let me know if you have any fears about merging this, or process tweaking ideas.

**Comment by asahi-badgeos** [comment]
Hi @lkraav ,

I actually am reluctant to merge this, since it will reboot the repository.  Instead, I can have my team just commit the changes from 1.4.8.2, which should be fairly straight forward from our end.

**Comment by lkraav** [comment]
> I actually am reluctant to merge this, since it will reboot the repository. Instead, I can have my team just commit the changes from 1.4.8.2, which should be fairly straight forward from our end.

@asahi-badgeos works for me. I think the only thing everyone's worried about is it might take some months.. :) But kidding aside, hoping to see it soon. Would be easier to maintain our patchset on top of a stable center.

**Pull request merged**
