### PR TITLE
Typo error in argument

### PR DESCRIPTION
**Pull request by X-Raym**
this made the function not works properly

### CODE REVIEW

**Comment by tw2113** [comment]
Cross post from #385

This is actually ending up being a big PR change, because of the fact that it affects a number of things in queries. 3 out of 4 internal calls to badgeos_get_achievements() don't set their own parameter and intend to rely on the intended default of 'any' BUUUUUUUT that's not getting set because of that typo.

You can see where we check for the value with the correct spelling inside badgeos_get_achievements_children_join() and badgeos_get_achievements_children_where(), both of which are callbacks for query filters. I'm praying that fixing it is not going to break anything, but will fix bugs that we may have going on that haven't been figured out yet.

**Comment by tw2113** [comment]
it's not going to be extremely intensive, but if you could toy with this being fixed and see if you encounter any issues or unexpected behavior in your site, I'd appreciate it. I just can't help but be nervous about fixing this and it causing issues.

**Comment by X-Raym** [comment]
I will test it in local, just in case.

**Comment by tw2113** [comment]
Been looking this one over.

As noted, these two callbacks use the achievement_relationship query parameter:
`badgeos_get_achievements_children_join()`
`badgeos_get_achievements_children_where()`

However, those callbacks are only added if the `children_of` parameter is passed in and set. The only time that `badgeos_get_achievements()` sets a `children_of` parameter, is in `badgeos_get_children_of_achievement()`.

A check of the codebase finds that the only time this function is used, including other addons, is in the core rules-engine.php file in the `badgeos_user_has_access_to_achievement` AND only if the achievement is sequential for steps.

With that said, I am more confident in that we won't break much by pulling it in.

That said, I have to close this PR because it's on the master branch, and we need it to be on the alpha branch. I will simply make the change myself, and give proper credit in the readme bullet point.

**Comment by X-Raym** [comment]
sounds good to me !

**Pull request closed without merging**
