### PR TITLE
do not treat '0' in meta values as empty

### PR DESCRIPTION
**Pull request by cherbst**
fixes '0' for maximum earnings being reset on reload

### CODE REVIEW

**Comment by reneneee** [comment]
Fixes https://github.com/opencredit/badgeos/issues/511

**Comment by reneneee** [comment]
And its duplicate: https://github.com/opencredit/badgeos/issues/380

**Comment by tw2113** [comment]
@cherbst @reneneee The biggest issue with this is that the cmb folder is actually a 3rd party library that BadgeOS makes use of, and is not something created for BadgeOS itself. It's also due for being updated to its successor version [CMB2](http://github.com/WebDevStudios/CMB2/), but hasn't happened yet.

Probably a better solution, long term here, would be to make it so it's compatible with "-1" for unlimited. Also for future pull requests, please issue them to the alpha branch, as that's our current dev version. Master branch is supposed to be release-ready at an point necessary, and matching the version on wordpress.org.

Leaving open for a bit more discussion if necessary.

**Comment by cherbst** [comment]
I was aware that this fix is against the CMB library and usually I would have send the pull request to them. But as you pointed out CMB is deprecated in favor of cmb2. So as BadgeOS uses it's own deprecated copy of CMB anyway, why not accept pull requests against it? As for your suggestion to use -1 instead of 0 I think it would be better for BC to keep the old behavior and make it just work and that's what this pull request does.
I will however send this against the alpha branch again and would be happy if you would merge it.

**Comment by tw2113** [comment]
The question is when the switch would be made. I believe I've proposed for it to be in the 1.5.0 version but am waiting to hear back on final decisions. I also have to believe even after the switch, a similar situation would surface with regards to string '0' and CMB2, putting us back at square one.

By all means feel free to leave in your own site so that you can do what you need to, but I'm hard pressed to merge in at the moment and release for everyone. I still think the '-1' value is a better long term route, and we could easily check and convert any saved ones in a user's database if necessary to not break back-compat.

**Comment by asahi-badgeos** [comment]
@reneneee ,

The underlying issue was resolved by specifying a -1 for unlimited earnings. I am closing this pull request.

**Pull request closed without merging**
