### PR TITLE
merge ORM into 2.0 branch

### PR DESCRIPTION
**Pull request by karnold**
implements ORM sub system to be further implemented.

### CODE REVIEW

**Comment by RugWarrior** [comment]
What is the status of this?

**Comment by tw2113** [comment]
Nothing new to report, sorry.

**Comment by karnold** [comment]
we have moved away from badgeos, so i wont be able to provide any maintenance or support for these code changes

**Comment by RugWarrior** [comment]
Do you changed to another solution (which?) or just away from badges?

**Comment by karnold** [comment]
Yes, We developed our own badging platform based on Laravel/OctoberCMS https://github.com/DallasMuseumArt/OctoberFriends

**Pull request closed without merging**
