### PR TITLE
congrats text bug fix

### PR DESCRIPTION
**Pull request by X-Raym**
implemented Oncevision bug fix.
https://wordpress.org/support/topic/congratulations-text-apostrophe-bug-report?replies=11#post-6445330

### CODE REVIEW

**Comment by X-Raym** [comment]
New FR translation updated.
Included fixes by Sime-O : https://github.com/opencredit/badgeos/pull/409
Note : the .mo file hasn't been generated.
Note : the grid view translation strings related to Sime-O hasn't been included.

**Comment by RugWarrior** [comment]
Is this still current?

**Comment by X-Raym** [comment]
Yes!

**Comment by solhuebner** [comment]
@tw2113 What about this PR?

**Comment by tw2113** [comment]
I'd need to look it over and try and recall the context etc. Regardless of that part, still needs to be issued against the Alpha branch and not master.

**Comment by X-Raym** [comment]
So that was the problem ?
Ask and you will be serve.

https://github.com/opencredit/badgeos/pull/455

**Comment by tw2113** [comment]
It will expedite the process, but I do want to test/confirm myself before doing the merge, and not sure when I'll get around to that.

**Pull request closed without merging**
